### ISSUE TITLE
Can't disable desaturation

### ISSUE THREAD

**Issue by k0nstruct** [CreativeMD/EnhancedVisuals#168]
The mod desaturates the colors on screen. Disabling the "desaturate" handler does nothing, but lowering its opacity to 0 makes everything black and white. Pressing F1 removes the effect, and if "doeffectsincreative" is disabled, you get full colors in creative too. I thought that was a feature for hunger, but it's always there apparently.
Before and after F1:
![2024-11-14_22 31 01](https://github.com/user-attachments/assets/9eae48b1-742b-4207-96e0-efe7fde795f2)
![2024-11-14_22 31 23](https://github.com/user-attachments/assets/3dda68b3-b0d1-4e08-a4dc-b2c27e1495ab)

**Comment by CreativeMD** [comment]
It is a feature for hunger, but it can take 1-2 minutes to adjust. I configured this effect to change very slow. You could either restart the game after disabling it or disable it when the screen is fully saturated. Furthermore you can disable the desaturate effect itself, but there was a bug which prevented this from happening. It is fixed in the newest version however.

**Comment by k0nstruct** [comment]
Thanks!
