### ISSUE TITLE
How to turn off Blood entirely in config?

### ISSUE THREAD

**Issue by mcb1013** [CreativeMD/EnhancedVisuals#39]
I disabled blood on hit in the config up towards the top, I also made the blood min and max time 0 so realistically it should never pop up. I have a friend who wants to play but has PTSD when it comes to blood splats so I need to completely 100% disable ALL blood. If anybody can help me figure out why its not working...

**Comment by CreativeMD** [comment]
There is a config file in `.minecraft/config/enhancedvisuals.cfg`. You have to set enabled to false in the following categories: `splatter-type`, `slash-type`,`pierce-type`,`impact-type` and maybe even `lowhealth-type` (heart beat overlay). This should disable all block effects.

**Comment by mcb1013** [comment]
Hey thank you for the fast reply! I've disabled all of those things and more, I disabled the blood splat min max time, drown min max, drown splashes set to 0, red overlay false, red overlay intensity set to 0, min max hit effect 0. Idk if these are blood related but they sounded like it so i disabled them. Anyways I disabled everything you said and more and it still splashes red every tick or every other tick while drowning...

**Comment by floral-qua-floral** [comment]
Howdy, @mcb1013. I'm rather squeamish personally so I can understand your friend's issue, and I also had a little trouble disabling all the blood effects through the config. I found it a lot easier to instead assemble a personal resource pack that replaces all blood splatters with empty textures, and I also recolored a handful of effects that I felt added to the mod so they'd be black and white, for a sort of tunnel-vision effect instead of a bloody overlay. This allows me to use the default config with all features enabled, and so long as I make sure the resource pack is enabled I can be 100% confident I won't encounter anything I'm not comfortable with, since I've gone through all the mod's assets and erased every trace of blood.

Just in case this might be something you'd want to use, I'll have the pack as a .zip attached at the bottom of this message! However, just so you know, I play the 1.12 version of the mod. I don't know if the format's changed for the 1.14 version. If your friend wants to play 1.14 (or any version of EnhancedVisuals that's not the most recent 1.12.2 release), please let me know so I can check to make sure the pack will work there, and ensure that everything I've changed applies correctly! I'd hate for them to load up my pack and then be surprised in-game because it wasn't up to date... If they _are_ on 1.12, though, this should do the job fine, if you want to take this approach. :) And, well, you'll have to excuse the pretty doofy pack.png icon, I just drew it in 4 seconds in MS paint when I made the pack. :P

Oh, one more thing - if your buddy would also be squicked out by the heartbeat sounds that play at low health, this resource pack does _not_ get rid of those. I could set it up to replace those with an empty sound file, though, if you'd want, or any other sort of low-health sound cue like from a Zelda game or something. Just let me know! (Of course, you're not obligated to use this if you're satisfied with using the config - I made this pack for myself, after all, so no pressure on you or your friend!)
[No Blood In Enhanced Visuals.zip](https://github.com/CreativeMD/EnhancedVisuals/files/4361977/No.Blood.In.Enhanced.Visuals.zip)

**Comment by CreativeMD** [comment]
If you are using the newest version you can disable the damage handler which should remove all blood effects.

@floral-qua-floral thanks for your help!

**Comment by nomino3390** [comment]
@mcb1013 @floral-qua-floral 
I combined [nox_cgt's pixelated texture pack](https://www.curseforge.com/minecraft/texture-packs/enhancedvisual-pixelated) with floral's no-blood texture pack to create a combined pixelated AND no blood texture pack. I thought I'd attach it here in case it's of any use to anyone. Works on enhancedvisuals version 1.6.7 and minecraft 1.20.1.

I kept two red overlays from the pixelated pack that weren't identifiable as blood after their pixelization and blurring, and kept the sounds that floral's pack removed.

[Pixelated_v1.3.1_EnhancedVisuals(nox_cgt, floral-qua-floral) visual blood removed, kept red overlays.zip](https://github.com/CreativeMD/EnhancedVisuals/files/12839766/Pixelated_v1.3.1_EnhancedVisuals.nox_cgt.floral-qua-floral.visual.blood.removed.kept.red.overlays.zip)
