### ISSUE TITLE
Minor incompatibility with IguanaTweaks Reborn

### ISSUE THREAD

**Issue by Jitreq** [CreativeMD/EnhancedVisuals#94]
When used with [https://www.curseforge.com/minecraft/mc-mods/iguanatweaks-reborn](https://www.curseforge.com/minecraft/mc-mods/iguanatweaks-reborn) and Explosion Overhaul is enabled in its config (enabled by default) explosion effects in EnhancedVisuals do not work.

EnhancedVisuals_FORGE_v1.5.5_mc1.18.2
CreativeCore_FORGE_v2.6.12_mc1.18.2
IguanaTweaksReborn-2.11.7-mc1.18.2
InsaneLib-1.5.1-mc1.18.2
Forge 40.1.60

**Comment by CreativeMD** [comment]
Hey, very very sorry for not responding earlier. Due to the fact EnhancedVisuals is developed for Forge and Fabric at the same time, these kind compatibilities are messy to implement. Furthermore I have dropped support for 1.18. Once IguanaTweaksReborn has updated to 1.19 you can let me know and I will try to fix it.
